[program:v2rays]
user=root
command=v2raya --v2ray-bin /home/sunyunbo/v2ray/v2ray -c /home/sunyunbo/v2ray -a 0.0.0.0:10806
numprocs=1
autostart=true
startsecs=3
autorestart=true
startretries=100000000000
redirect_stderr=true
stdout_logfile=/var/log/supervisor/v2rays.log
stdout_logfile_maxbytes=500MB
stdout_logfile_backups=10
